# Generated by Django 3.1.1 on 2020-09-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
    ]
